name: listeria
favicon: null
layout_spectrum: 0.5593131894711405
typography_spectrum: 0.5234160001855344
title: 'DOWNLOADABLE MEDIA LIST APPS FOR CREATIVE BUSINESS '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bbb6b9'
    - '#010000'
    - '#56495d'
    - '#d31f1f'
  brandStrength: 0.25
  lightness: 0.8526363573037088
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
